### PR TITLE
Fixes for Issue #57

### PR DESCRIPTION
**Pull request by MitchellGerdisch**
In a nutshell, changed outputvalues and outputkeys to be arrays instead of simple_elements.

Updated the test CAT to show how to return the outputs.
If there's some clever way to merge two arrays into a hash, please let me know since that would be prettier code.

Tested the test CAT as well as nested CFT CAT and the "RedShift CFT" CAT in demo.

### CODE REVIEW

**Comment by rshade** [comment]
can you update the readme and changelog?

**Comment by rshade** [comment]
thanks @MitchellGerdisch btw, looks great

**Comment by dfrankel33** [comment]
@rshade @MitchellGerdisch the readme prob doesn't need an update since the only change is simple_element -> array.  version up in the changelog to v1.1 

also, can you add a long_description to the plugin file to read: "Version: 1.1".  we started adding that after this was published.

**Comment by MitchellGerdisch** [comment]
Versioning info added to changelog and plugin file.

**Pull request merged**
